config/routes.rb
Rails.application.routes.draw do

  apipie
  #
  # Web Application
  #
  resources :virtual_races
  resources :metrics
  mount FullcalendarEngine::Engine => "/trainingplan"
  
  resources :trainingplans
  resources :planedunits
  resources :unitpools
  resources :workouts
  resources :zones
  resources :comments

  root to: 'landing#index'
  get 'dashboards/dashboard_0'
  get 'dashboards/dashboard_1'
  
  get 'racepaces/index'
  
   # All routes
  get "virtual_race/race_view"
  
  
  # Jasmine
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # Devise
  devise_for :users

  # EasyCaptcha
  match 'captcha', to: EasyCaptcha::Controller.action(:captcha), via: :get
  
  # Root route
  #root 'imported_race_results#search'
  # root 'visitors#home'
  
  # VisitorsController
  get 'visitors/home'

  # UsersController
  resources :users, only: [ :index, :show ] do
    match 'roles', to: 'users#show_roles', via: [ :get ]
    match 'roles', to: 'users#update_roles', via: [ :patch, :put ]
    match 'users/:id', to: 'users#show', via: :get
  end

  resources :users do
    member do
      get :follow
      get :stop_following
    end
  end

  # PreferencesController
  resources :preferences, only: [ :show, :update ]

  # GroupsController
  resources :groups

  # ImportedRaceResultsController
  get  'imported_race_results/search'
  post 'imported_race_results/search'
  get "appviews/profile"

  match 'imported_race_results/add_new_comment' => 'imported_race_results#add_new_comment', :as => 'add_new_comment_to_posts', :via => [:post]
  match 'imported_race_results/:id/like' => 'imported_race_results#like', :as => 'like_imported_race_result', :via => [:get]
  match 'imported_race_results/:id/unlike' => 'imported_race_results#unlike', :as => 'unlike_imported_race_result', :via => [:get]
  
  match '/users/:id/allocate_race_result',    to: 'users#allocate_race_result',    via: 'get', :as => :allocate_race_result
  match '/users/:id/unallocate_race_result',    to: 'users#unallocate_race_result',    via: 'get', :as => :unallocate_race_result

  match '/tools/calc_vdot', to: 'tools#calc_vdot', via: 'get', :as => :calc_vdot
  match '/tools/qualigel', to: 'tools#qualigel', via: 'get', :as => :qualigel
  
  resources :imported_race_results, only: [ :show ]


  #
  # API
  #

  namespace :api, defaults: { format: :json }, path: '/api'  do

    #
    # v1
    #

    namespace :v1 do
    
      # ImportedRaceResultsController
      get 'imported_race_results/search'
      
      resources :imported_race_results, only: [ :show ]

      # PreferencesController
      resources :preferences, only: [ :show, :update ]
      
      # GroupsController
      resources :groups

    end
  
  end

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :sport_type
  belongs_to :trainingplan
  has_one :event, class_name: "::FullcalendarEngine::Event", as: :ev, dependent: :destroy
  has_many :laps, dependent: :destroy

  #has_many :event_series, class_name: "::FullcalendarEngine::EventSeries", foreign_key: "trainingplan_id", dependent: :destroy
  
  has_attached_file :workout_file
  	validates_attachment_content_type :workout_file, :content_type => ["application/octet-stream", "application/xml"]

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  skip_before_action :authenticate_user!
  
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  before_action :set_workout, only: [:show, :edit, :update, :destroy]

  # GET /workouts
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1
  def show
    workout_filename=Paperclip.io_adapters.for(@workout.workout_file).path
    
    if workout_filename[-3..-1] == "tcx" or workout_filename[-3..-1] == "TCX"
      doc=Hash.from_xml(File.read(workout_filename))
      @doc = doc
      @creator_name = doc["TrainingCenterDatabase"]["Activities"]["Activity"]["Creator"]["Name"]
      @creator_unitid = doc["TrainingCenterDatabase"]["Activities"]["Activity"]["Creator"]["UnitId"]
      @creator_version = "#{doc["TrainingCenterDatabase"]["Activities"]["Activity"]["Creator"]["Version"]["VersionMajor"]}.#{doc["TrainingCenterDatabase"]["Activities"]["Activity"]["Creator"]["Version"]["VersionMinor"]}"
      @author_name = doc["TrainingCenterDatabase"]["Author"]["Name"]
      @author_build_version = "#{doc["TrainingCenterDatabase"]["Author"]["Build"]["Version"]["VersionMajor"]}.#{doc["TrainingCenterDatabase"]["Activities"]["Activity"]["Creator"]["Version"]["VersionMinor"]}"
      @author_langid = doc["TrainingCenterDatabase"]["Author"]["LangID"]
      @author_partnumber = doc["TrainingCenterDatabase"]["Author"]["PartNumber"]

      @activity_sport = doc["TrainingCenterDatabase"]["Activities"]["Activity"]["Sport"]
      @activity_id = doc["TrainingCenterDatabase"]["Activities"]["Activity"]["Id"]
    
      @laps = doc["TrainingCenterDatabase"]["Activities"]["Activity"]["Lap"].count.to_s
    end
    
    lap_num=0
    @marker_hash = Gmaps4rails.build_markers(@workout.laps) do | lap, marker| 
      lap_num+=1
      if lap.track.trackpoints.count > 0 #if there is a trackpoint
        marker.lat lap.track.trackpoints.last.tplatitudedegrees
        marker.lng lap.track.trackpoints.last.tplongitudedegrees
        marker.infowindow "Lap #{lap_num.to_s}\n Lap-Distance: #{lap.lpdistancemeters.round(2)}m"
        marker.picture({
          "picture" => 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=A|FF0000|000000',
          "width" =>  '16',        
          "height" => '16'
          })
        marker.json({:title => "laptitel"})
      end
    end

    @polylines=[]
    polyline=[]
    @workout.laps.each do | lap |
      @track=lap.track
      @track.trackpoints.each do | trackpoint |
          polyline << {"lng": trackpoint.tplongitudedegrees, "lat": trackpoint.tplatitudedegrees }
        end
      @polylines << polyline #polylines for gmaps
    end

  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  def create
    if current_user
      @workout = current_user.workouts.create(workout_params)
      if @workout.save
        workout_file_with_path=Paperclip.io_adapters.for(@workout.workout_file).path
        tcx_json = Tcxtools.parse_tcx_file(workout_file_with_path)
        tcx_hash = JSON.parse(tcx_json)
        

        tcx_hash['laps'].each do | lap_hash |
          #create all laps
          lap=@workout.laps.create(lap_hash.except('track'))
          #create a track for each lap
          track=Track.create(lap_id: lap.id)
          trackpoints_hash=lap_hash['track']['trackpoints']
          #fixme add a rails progressbar
          #bar= ProgressBar.new(trackpoints.count, :bar, :counter, :eta)
          trackpoints_hash.each do |trackpoint_hash| 
            track.trackpoints.create(trackpoint_hash)
            #bar.increment!
          end
        end

        #create a fullcalendar event
        unless tcx_hash["activity_datetimeid"].nil?
          @workout.update(completed_datetime: tcx_hash["activity_datetimeid"])
          @workout.build_event(title: "TXC #{tcx_hash["activity_datetimeid"]}", 
              description: "-", 
              starttime: tcx_hash["activity_datetimeid"].to_datetime, 
              endtime: tcx_hash["activity_datetimeid"].to_datetime+2.hours, 
              all_day: false).save
              #fixme: endtime should be starttime + activity_duration
        end
        redirect_to :back, notice: 'Workout was successfully created.'
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
        redirect_to :back, notice: 'Failed to create workout'
      end
    else
        redirect_to :back, notice: 'Have to be logged in'
    end

  end

  # PATCH/PUT /workouts/1
  def update
    if @workout.update(workout_params)
      redirect_to @workout, notice: 'Workout was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /workouts/1
  def destroy
    @workout.destroy
    redirect_to workouts_url, notice: 'Workout was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def workout_params
      params.require(:workout).permit(:sport_type_id, :title, :description, :planed_duration, :completed_duration, :planed_distance, :completed_distance, :planed_avg_pace, :completed_avg_pace, :planed_avg_speed, :completed_avg_speed, :planed_calories, :completed_calories, :planed_elevation_gain, :completed_elevation_gain, :completed_elevation_high, :completed_elevation_low, :planed_tss, :completed_tss, :planed_if, :completed_if, :planed_avg_hr, :completed_avg_hr, :completed_min_hr, :completed_max_hr, :planed_avg_power, :completed_avg_power, :completed_min_power, :completed_max_power, :autor, :target, :days_before_race, :planed_datetime, :completed_datetime, :athlete_id, :coach_id, :workout_file)
    end
end

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workouts</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Sport type</th>
      <th>Title</th>
      <th>Description</th>
      <th>Planed duration</th>
      <th>Completed duration</th>
      <th>Planed distance</th>
      <th>Completed distance</th>
      <th>Planed avg pace</th>
      <th>Completed avg pace</th>
      <th>Planed avg speed</th>
      <th>Completed avg speed</th>
      <th>Planed calories</th>
      <th>Completed calories</th>
      <th>Planed elevation gain</th>
      <th>Completed elevation gain</th>
      <th>Completed elevation high</th>
      <th>Completed elevation low</th>
      <th>Planed tss</th>
      <th>Completed tss</th>
      <th>Planed if</th>
      <th>Completed if</th>
      <th>Planed avg hr</th>
      <th>Completed avg hr</th>
      <th>Completed min hr</th>
      <th>Completed max hr</th>
      <th>Planed avg power</th>
      <th>Completed avg power</th>
      <th>Completed min power</th>
      <th>Completed max power</th>
      <th>Autor</th>
      <th>Target</th>
      <th>Days before race</th>
      <th>Planed datetime</th>
      <th>Completed datetime</th>
      <th>Athlete</th>
      <th>Coach</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% current_user && current_user.workouts.includes(:sport_type).order(id: :desc).each do |workout| %>
      <tr>
        <td><%= link_to workout.id, workout  %></td>
        <td><%= workout.sport_type %></td>
        <td><%= workout.title %></td>
        <td><%= workout.description %></td>
        <td><%= workout.planed_duration %></td>
        <td><%= workout.completed_duration %></td>
        <td><%= workout.planed_distance %></td>
        <td><%= workout.completed_distance %></td>
        <td><%= workout.planed_avg_pace %></td>
        <td><%= workout.completed_avg_pace %></td>
        <td><%= workout.planed_avg_speed %></td>
        <td><%= workout.completed_avg_speed %></td>
        <td><%= workout.planed_calories %></td>
        <td><%= workout.completed_calories %></td>
        <td><%= workout.planed_elevation_gain %></td>
        <td><%= workout.completed_elevation_gain %></td>
        <td><%= workout.completed_elevation_high %></td>
        <td><%= workout.completed_elevation_low %></td>
        <td><%= workout.planed_tss %></td>
        <td><%= workout.completed_tss %></td>
        <td><%= workout.planed_if %></td>
        <td><%= workout.completed_if %></td>
        <td><%= workout.planed_avg_hr %></td>
        <td><%= workout.completed_avg_hr %></td>
        <td><%= workout.completed_min_hr %></td>
        <td><%= workout.completed_max_hr %></td>
        <td><%= workout.planed_avg_power %></td>
        <td><%= workout.completed_avg_power %></td>
        <td><%= workout.completed_min_power %></td>
        <td><%= workout.completed_max_power %></td>
        <td><%= workout.autor %></td>
        <td><%= workout.target %></td>
        <td><%= workout.days_before_race %></td>
        <td><%= workout.planed_datetime %></td>
        <td><%= workout.completed_datetime %></td>
        <td><%= workout.athlete_id %></td>
        <td><%= workout.coach_id %></td>
        <td><%= link_to 'Show', workout %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
        <td><%= link_to 'Destroy', workout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<div class="row">
    <div class="col-lg-9">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Workout Chart
                    <small><%= @workout.workout_file_file_name%></small>
                </h5>
            </div>
            <div class="ibox-content">
                <div>
                    <div id="workoutChart"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Workout Info</h5>
            </div>
            <div class="ibox-content">
                <div>
                  <p><strong>Creator Name:</strong><%= @creator_name %></p>
                  <p><strong>Creator Unit ID:</strong><%= @creator_unitid %></p> 
                  <p><strong>Creator Version:</strong><%= @creator_version %></p> 
                  <p><strong>Author Name:</strong><%= @author_name %></p> 
                  <p><strong>Author Build Version:</strong><%= @author_build_version %></p> 
                  <p><strong>Author LangID:</strong><%= @author_langid %></p> 
                  <p><strong>Author Part Number:</strong><%= @author_partnumber %></p>
                  <p><strong>Activity Sport Type:</strong><%= @activity_sport %></p> 
                  <p><strong>Activity ID:</strong><%= @activity_id %></p> 
                </div>
            </div>
        </div>
    </div>
</div>


  <div class="row">
  <div class="ibox-content">
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>Lap</th>
            <th>Time</th>
            <th>Distance</th>
            <th>MaxSpeed</th>
            <th>Calories</th>
            <th>Avg HR</th>
            <th>Max HR</th>
           </tr>
          </thead>
          <tbody>
            <% lap_num = 0 %>
            <% @workout.laps.each do | lap | %>
              <% lap_num+=1 %>
      
            <tr>
              <td><%= lap_num.to_s%></td>
              <td><%= "#{Time.at(lap.lptotaltimeseconds).utc.strftime("%H:%M:%S")}" %></td>
              <td><%= "#{lap.lpdistancemeters}m" %></td>
              <td><%= "#{lap.lpmaxspeed.to_f.round(2)}m/s" %></td>
              <td><%= "#{lap.lpcalories}cal" %></td>
              <td><%= "#{lap.lpavgheartratebpm}bpm" %></td>
              <td><%= "#{lap.lpmaxheartratebpm}bpm" %></td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
  </div>
</div>
 

<p>
  <strong>Sport type:</strong>
  <%= @workout.sport_type %>
</p>

<p>
  <strong>Title:</strong>
  <%= @workout.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workout.description %>
</p>

<p>
  <strong>Planed duration:</strong>
  <%= @workout.planed_duration %>
</p>

<p>
  <strong>Completed duration:</strong>
  <%= @workout.completed_duration %>
</p>

<p>
  <strong>Planed distance:</strong>
  <%= @workout.planed_distance %>
</p>

<p>
  <strong>Completed distance:</strong>
  <%= @workout.completed_distance %>
</p>

<p>
  <strong>Planed avg pace:</strong>
  <%= @workout.planed_avg_pace %>
</p>

<p>
  <strong>Completed avg pace:</strong>
  <%= @workout.completed_avg_pace %>
</p>

<p>
  <strong>Planed avg speed:</strong>
  <%= @workout.planed_avg_speed %>
</p>

<p>
  <strong>Completed avg speed:</strong>
  <%= @workout.completed_avg_speed %>
</p>

<p>
  <strong>Planed calories:</strong>
  <%= @workout.planed_calories %>
</p>

<p>
  <strong>Completed calories:</strong>
  <%= @workout.completed_calories %>
</p>

<p>
  <strong>Planed elevation gain:</strong>
  <%= @workout.planed_elevation_gain %>
</p>

<p>
  <strong>Completed elevation gain:</strong>
  <%= @workout.completed_elevation_gain %>
</p>

<p>
  <strong>Completed elevation high:</strong>
  <%= @workout.completed_elevation_high %>
</p>

<p>
  <strong>Completed elevation low:</strong>
  <%= @workout.completed_elevation_low %>
</p>

<p>
  <strong>Planed tss:</strong>
  <%= @workout.planed_tss %>
</p>

<p>
  <strong>Completed tss:</strong>
  <%= @workout.completed_tss %>
</p>

<p>
  <strong>Planed if:</strong>
  <%= @workout.planed_if %>
</p>

<p>
  <strong>Completed if:</strong>
  <%= @workout.completed_if %>
</p>

<p>
  <strong>Planed avg hr:</strong>
  <%= @workout.planed_avg_hr %>
</p>

<p>
  <strong>Completed avg hr:</strong>
  <%= @workout.completed_avg_hr %>
</p>

<p>
  <strong>Completed min hr:</strong>
  <%= @workout.completed_min_hr %>
</p>

<p>
  <strong>Completed max hr:</strong>
  <%= @workout.completed_max_hr %>
</p>

<p>
  <strong>Planed avg power:</strong>
  <%= @workout.planed_avg_power %>
</p>

<p>
  <strong>Completed avg power:</strong>
  <%= @workout.completed_avg_power %>
</p>

<p>
  <strong>Completed min power:</strong>
  <%= @workout.completed_min_power %>
</p>

<p>
  <strong>Completed max power:</strong>
  <%= @workout.completed_max_power %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @workout.autor %>
</p>

<p>
  <strong>Target:</strong>
  <%= @workout.target %>
</p>

<p>
  <strong>Days before race:</strong>
  <%= @workout.days_before_race %>
</p>

<p>
  <strong>Planed datetime:</strong>
  <%= @workout.planed_datetime %>
</p>

<p>
  <strong>Completed datetime:</strong>
  <%= @workout.completed_datetime %>
</p>

<p>
  <strong>Athlete:</strong>
  <%= @workout.athlete_id %>
</p>

<p>
  <strong>Coach:</strong>
  <%= @workout.coach_id %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout) %> |
<%= link_to 'Back', workouts_path %>


<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Virtual Race</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">Home</a>
        </li>
        <li>
            <a>Miscellaneous</a>
        </li>
        <li class="active">
            <strong>Virtual Race Nr.1</strong>
        </li>
    </ol>
</div>
<div class="col-lg-2">

</div>
        </div>

<div class="wrapper wrapper-content  animated fadeInRight">

<div class="row">
    <div class="col-md-12">
        <div class="ibox ">
            <div class="ibox-title">
                <h5><%=@workout.workout_file_file_name.to_s if @workout%></h5>
            </div>
            <div class="ibox-content">
              <div class="google-map" id="map"></div>
            </div>
        </div>
    </div>

<div class="row">
  <div class="ibox-content">
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
          <tr>
            <th>ID</th>
            <th>Lng</th>
            <th>Lat</th>
            <th>Alt</th>
            <th>Speed</th>
           </tr>
          </thead>
          <tbody>
            <% @track && @track.trackpoints.limit(10).each do |trackpoint| %>
            <tr>
              <td><%=trackpoint.id.to_s%></td>
              <td><%=trackpoint.tplongitudedegrees.to_f %></td>
              <td><%=trackpoint.tplatitudedegrees.to_f %></td>
              <td><%=trackpoint.tpaltitudemeters.to_f %>m</td>
              <td><%=trackpoint.tpspeed.to_f.round(1) %>m/s</td>
            </tr>
            <%end%>
          </tbody>
        </table>
      </div>
  </div>
</div>

<% content_for :javascript do %>
<!--
 You need to include this script on any page that has a Google Map.
 When using Google Maps on your own site you MUST signup for your own API key at:
 https://developers.google.com/maps/documentation/javascript/tutorial#api_key
 After your sign up replace the key in the URL below..
-->
<!--script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDQTpXj82d8UpCi97wzo_nKXL7nYrd4G70"></script-->
<script src="//maps.google.com/maps/api/js?v=3.23&key=AIzaSyDQTpXj82d8UpCi97wzo_nKXL7nYrd4G70"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<script type="text/javascript">
// When the window has finished loading google map
 //"lat": 51.0292,
 //"lng": 6.23371,
     

handler = Gmaps.build('Google');
handler.buildMap({
    provider: {
      disableDefaultUI: false
      // pass in other Google Maps API options here
    },
    internal: {
      id: 'map'
    }
  },
  function(){

    c3.generate({
      bindto: '#workoutChart',
      data:{
          columns: [
            ['Speed', 
              <% @workout.laps.each do | lap | %>
                <% lap.track.trackpoints.each do | trackpoint | %>
                  <%= trackpoint.tpspeed.to_f %> , 
                <% end %>  
              <% end %>  
            ],

            ['Heartrate', 
              <% @workout.laps.each do | lap | %>
                <% lap.track.trackpoints.each do | trackpoint | %>
                  <%= trackpoint.tpheartratebpm.to_f %> , 
                <% end %>  
              <% end %>  
            ],
            ['Altitude', 
              <% @workout.laps.each do | lap | %>
                <% lap.track.trackpoints.each do | trackpoint | %>
                  <%= trackpoint.tpaltitudemeters.to_f %> , 
                <% end %>  
              <% end %>  
            ]

            ],
            colors:{
                data1: '#1ab394',
                data2: '#BABABA'
            }
        }
    });

    markers = handler.addMarkers(<%=raw @marker_hash.to_json %>);
    //polyline = [{"lat":45.678295,"lng":6.603813,"ele":438.626221,"time":1381851321},{"lat":45.678196,"lng":6.603607,"ele":423.202148,"time":1381851363},{"lat":45.678181,"lng":6.603607,"ele":421.108398,"time":1381851373},{"lat":45.678162,"lng":6.603584,"ele":420.153442,"time":1381851383},{"lat":45.678123,"lng":6.603569,"ele":422.561096,"time":1381851393},{"lat":45.678165,"lng":6.6036,"ele":425.191284,"time":1381851403},{"lat":45.678169,"lng":6.603607,"ele":425.262329,"time":1381851413}];
    //handler.bounds.extendWith(polylines);
    <% @polylines.each do |polyline| %>
      polyline = <%=raw polyline.to_json %>
      handler.addPolyline(polyline);
      handler.bounds.extend(polyline[0]);
      handler.bounds.extend(polyline[ polyline.length - 1]);
    <% end %>
    /*markers = handler.addMarkers([
      {
          "lat": 51.0292,
          "lng": 6.23371,
          "picture": {
          "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
          "width":  32,
          "height": 32
        },
        "infowindow": "hello!"
      }
    ]);*/
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  }
);

</script>

<% end %>