config/routes.rb
Rails.application.routes.draw do

  apipie
  #
  # Web Application
  #
  resources :virtual_races
  resources :metrics
  mount FullcalendarEngine::Engine => "/trainingplan"
  
  resources :trainingplans
  resources :planedunits
  resources :unitpools
  resources :workouts
  resources :zones
  resources :comments

  root to: 'landing#index'
  get 'dashboards/dashboard_0'
  get 'dashboards/dashboard_1'
  
  get 'racepaces/index'
  
   # All routes
  get "virtual_race/race_view"
  
  
  # Jasmine
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # Devise
  devise_for :users

  # EasyCaptcha
  match 'captcha', to: EasyCaptcha::Controller.action(:captcha), via: :get
  
  # Root route
  #root 'imported_race_results#search'
  # root 'visitors#home'
  
  # VisitorsController
  get 'visitors/home'

  # UsersController
  resources :users, only: [ :index, :show ] do
    match 'roles', to: 'users#show_roles', via: [ :get ]
    match 'roles', to: 'users#update_roles', via: [ :patch, :put ]
    match 'users/:id', to: 'users#show', via: :get
  end

  resources :users do
    member do
      get :follow
      get :stop_following
    end
  end

  # PreferencesController
  resources :preferences, only: [ :show, :update ]

  # GroupsController
  resources :groups

  # ImportedRaceResultsController
  get  'imported_race_results/search'
  post 'imported_race_results/search'
  get "appviews/profile"

  match 'imported_race_results/add_new_comment' => 'imported_race_results#add_new_comment', :as => 'add_new_comment_to_posts', :via => [:post]
  match 'imported_race_results/:id/like' => 'imported_race_results#like', :as => 'like_imported_race_result', :via => [:get]
  match 'imported_race_results/:id/unlike' => 'imported_race_results#unlike', :as => 'unlike_imported_race_result', :via => [:get]
  
  match '/users/:id/allocate_race_result',    to: 'users#allocate_race_result',    via: 'get', :as => :allocate_race_result
  match '/users/:id/unallocate_race_result',    to: 'users#unallocate_race_result',    via: 'get', :as => :unallocate_race_result

  match '/tools/calc_vdot', to: 'tools#calc_vdot', via: 'get', :as => :calc_vdot
  match '/tools/qualigel', to: 'tools#qualigel', via: 'get', :as => :qualigel
  
  resources :imported_race_results, only: [ :show ]


  #
  # API
  #

  namespace :api, defaults: { format: :json }, path: '/api'  do

    #
    # v1
    #

    namespace :v1 do
    
      # ImportedRaceResultsController
      get 'imported_race_results/search'
      
      resources :imported_race_results, only: [ :show ]

      # PreferencesController
      resources :preferences, only: [ :show, :update ]
      
      # GroupsController
      resources :groups

    end
  
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3, maximum: 256 }
  validates :description, length: { maximum: 16384 }

  resourcify #allow assignment of this resource to a role (rolify gem)

end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < Api::V1::ApplicationController

  before_action :set_group, only: [ :show, :edit, :update, :destroy ]



  api! 'Return the list of all groups'
  def index
    @groups = policy_scope(Group.all)
    authorize @groups

    respond_to do |format|
      format.json { render json: @groups }
    end
  end

  api! "Show group specified by id"
  param :id, :number, "ID of the group" 
  def show
    respond_to do |format|
      format.json { render json: @group }
    end
  end

  api! "New group (without beeing saved)"
  def new
    @group = Group.new
    authorize @group
    
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  api! "Edit group"
  param :id, :number, "ID of the group to edit" 
  def edit
    show
  end

  api! "Create new group"
  def create
    @group = Group.new(group_params)
    authorize @group
    
    respond_to do |format|
      if @group.save
        format.json { render json: @group, status: :created }
      else
        format.json { render json: @group, status: :unprocessable_entity, serializer: ActiveModel::Serializer::ErrorSerializer }
      end
    end
  end

  api! "Update group parameter"
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.json { render json: @group }
      else
        format.json { render json: @group, status: :unprocessable_entity, serializer: ActiveModel::Serializer::ErrorSerializer }
      end
    end
  end

  api! "Delete group"
  def destroy
    @group.destroy
    
    respond_to do |format|
      format.json { head status: :no_content }
    end
  end

private

  def set_group
    begin
      @group = Group.find(params[:id])
      begin
        authorize @group
      rescue
        head status: :unauthorized
      end
    rescue
      head status: :not_found
    end
  end

  def group_params
    params.require(:group).permit(*policy(@group || Group).permitted_attributes)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # Allow access without login.
  skip_before_action :authenticate_user!
  
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = policy_scope(Group.all)
    authorize @groups
  end

  def show
  end

  def new
    @group = Group.new
    authorize @group
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    authorize @group

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_group
    @group = Group.find(params[:id])
    authorize @group
  end

  def group_params
    params.require(:group).permit(*policy(@group || Group).permitted_attributes)
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.haml
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/groups/edit.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.haml
%h1 Listing groups

%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @groups.each do |group|
      %tr
        %td= group.name
        %td= group.description
        %td= link_to 'Show', group
        %td= link_to 'Edit', edit_group_path(group)
        %td= link_to 'Destroy', group, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Group', new_group_path

app/views/groups/index.html.erb
<% title "Teams" %>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Teams board</h2>
        <ol class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a>App views</a>
            </li>
            <li class="active">
                <strong>Teams board</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <% Group.all.each do |group|%>
          <div class="col-lg-4">
            <div class="ibox">
                <div class="ibox-title">
                    <span class="label label-primary pull-right">NEW</span>
                    <h5><%="#{group.name} fixme members)"%></h5>
                </div>
                <div class="ibox-content">
                    <div class="team-members">
                        <!--fixme-->
                        <%User.limit(10).each do |user| %>
                            <a href="#"><img alt="member" class="img-circle" src="<%= image_path('a'+rand(1..8).to_s+'.jpg') %>"></a>
                        <%end%>    
                        <!--fixme-->
                        <%User.limit(10).each do |user| %>
                            <%=user.email.split('@')[0]%>
                            <br>
                        <%end%>
                    </div>
                    <h4>Info about Team</h4>
                    <p>
                        It is a long established fact that a reader will be distracted by the readable content
                        of a page when looking at its layout. The point of using Lorem Ipsum is that it has.
                    </p>
                    <div>
                        <span>Status of collected vdot point:</span>
                        <div class="stat-percent">48%</div>
                        <div class="progress progress-mini">
                            <div style="width: 48%;" class="progress-bar"></div>
                        </div>
                    </div>
                    <div class="row  m-t-sm">
                        <div class="col-sm-4">
                            <div class="font-bold">Total km</div>
                            12000
                        </div>
                        <div class="col-sm-4">
                            <div class="font-bold">RANKING</div>
                            4th
                        </div>
                        <div class="col-sm-4 text-right">
                            <div class="font-bold">Vdot-Level</div>
                            91.3 <i class="fa fa-level-up text-navy"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      <%end%>    
    </div>


</div>

app/views/groups/new.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.haml
%p#notice= notice

%p
  %b Name:
  = @group.name
%p
  %b Description:
  = @group.description

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path