config/routes.rb
Rails.application.routes.draw do

  apipie
  #
  # Web Application
  #
  resources :virtual_races
  resources :metrics
  mount FullcalendarEngine::Engine => "/trainingplan"
  
  resources :trainingplans
  resources :planedunits
  resources :unitpools
  resources :workouts
  resources :zones
  resources :comments

  root to: 'landing#index'
  get 'dashboards/dashboard_0'
  get 'dashboards/dashboard_1'
  
  get 'racepaces/index'
  
   # All routes
  get "virtual_race/race_view"
  
  
  # Jasmine
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # Devise
  devise_for :users

  # EasyCaptcha
  match 'captcha', to: EasyCaptcha::Controller.action(:captcha), via: :get
  
  # Root route
  #root 'imported_race_results#search'
  # root 'visitors#home'
  
  # VisitorsController
  get 'visitors/home'

  # UsersController
  resources :users, only: [ :index, :show ] do
    match 'roles', to: 'users#show_roles', via: [ :get ]
    match 'roles', to: 'users#update_roles', via: [ :patch, :put ]
    match 'users/:id', to: 'users#show', via: :get
  end

  resources :users do
    member do
      get :follow
      get :stop_following
    end
  end

  # PreferencesController
  resources :preferences, only: [ :show, :update ]

  # GroupsController
  resources :groups

  # ImportedRaceResultsController
  get  'imported_race_results/search'
  post 'imported_race_results/search'
  get "appviews/profile"

  match 'imported_race_results/add_new_comment' => 'imported_race_results#add_new_comment', :as => 'add_new_comment_to_posts', :via => [:post]
  match 'imported_race_results/:id/like' => 'imported_race_results#like', :as => 'like_imported_race_result', :via => [:get]
  match 'imported_race_results/:id/unlike' => 'imported_race_results#unlike', :as => 'unlike_imported_race_result', :via => [:get]
  
  match '/users/:id/allocate_race_result',    to: 'users#allocate_race_result',    via: 'get', :as => :allocate_race_result
  match '/users/:id/unallocate_race_result',    to: 'users#unallocate_race_result',    via: 'get', :as => :unallocate_race_result

  match '/tools/calc_vdot', to: 'tools#calc_vdot', via: 'get', :as => :calc_vdot
  match '/tools/qualigel', to: 'tools#qualigel', via: 'get', :as => :qualigel
  
  resources :imported_race_results, only: [ :show ]


  #
  # API
  #

  namespace :api, defaults: { format: :json }, path: '/api'  do

    #
    # v1
    #

    namespace :v1 do
    
      # ImportedRaceResultsController
      get 'imported_race_results/search'
      
      resources :imported_race_results, only: [ :show ]

      # PreferencesController
      resources :preferences, only: [ :show, :update ]
      
      # GroupsController
      resources :groups

    end
  
  end

end

app/models/trainingplan.rb
class Trainingplan < ActiveRecord::Base
  belongs_to :user
  has_many :planedunit, dependent: :destroy
  has_many :workout, dependent: :destroy

  resourcify #allow assignment of this resource to a role (rolify gem)

end

app/controllers/trainingplans_controller.rb
class TrainingplansController < ApplicationController

  skip_before_action :authenticate_user!
  
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  before_action :set_trainingplan, only: [:show, :edit, :update, :destroy]

  # GET /trainingplans
  # GET /trainingplans.json
  def index

    #update selected colors and show options
    params[:trainingplan_ids] && params[:trainingplan_ids].each_with_index do |id, index|
      Trainingplan.find_by_id(id).update(color: params[:trainingplan_colors][index])
      if params[:show_ids].to_a.include?(id) #then it should be shown
       Trainingplan.find_by_id(id).update(show: true)
      else
       Trainingplan.find_by_id(id).update(show: false)
      end
    end 

    @trainingplans = Trainingplan.all
    if current_user.nil?
      @my_trainingplans = []
    else
      #get current assigned trainingplans 
      @my_trainingplans = current_user.trainingplans
    end
  end

  # GET /trainingplans/1
  # GET /trainingplans/1.json
  def show
    gon.events_title=[]
    @events_title = []
    gon.events_startdatetime = []
    @events_startdatetime = []
    @trainingplan.workout.each do |workout| 
       gon.events_title << workout.title
       gon.events_startdatetime << workout.planed_datetime
  end
   # commontator_thread_show(@trainingplan)
  end

  # GET /trainingplans/new
  def new
    @trainingplan = Trainingplan.new
    @trainingplan.update(user_id: current_user.id)
  end

  # GET /trainingplans/1/edit
  def edit
  end

  # POST /trainingplans
  # POST /trainingplans.json
  def create
    @trainingplan = Trainingplan.new(trainingplan_params)

    respond_to do |format|
      if @trainingplan.save
        format.html { redirect_to @trainingplan, notice: 'Trainingplan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trainingplan }
      else
        format.html { render action: 'new' }
        format.json { render json: @trainingplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainingplans/1
  # PATCH/PUT /trainingplans/1.json
  def update
    respond_to do |format|
      if @trainingplan.update(trainingplan_params)
        format.html { redirect_to @trainingplan, notice: 'Trainingplan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trainingplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainingplans/1
  # DELETE /trainingplans/1.json
  def destroy
    @trainingplan.destroy
    respond_to do |format|
      format.html { redirect_to trainingplans_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainingplan
      @trainingplan = Trainingplan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainingplan_params
      params.require(:trainingplan).permit(:Athlete_id, :tpracedate, :tpracetime, :tpunitsperweek)
    end
end

app/views/trainingplans/_form.haml
= simple_form_for @trainingplan do |f|
  = f.input :tpracedate
  = f.input :tpracetime
  = f.input :tpunitsperweek
  = f.button :submit

.loginColumns.animated.fadeInDown
  .row
    .col-md-6
      %h2
        .font-bold  Welcome to RACEsPACE
        %small I can't tell you why but I know for shure that this is exactly the tool which all enduance athletes were waiting for.
    .col-md-6
      .ibox-content
      = simple_form_for @trainingplan do |f|
        = f.input :tpracedate
        = f.input :tpracetime
        = f.input :tpunitsperweek
        = f.button :submit
  %hr
  .row
    .col-md-6 Copyright RACEsPACE GmbH
    .col-md-6.text.right.small © 2015-2016

app/views/trainingplans/edit.html.erb
<h1>Editing Trainingplan</h1>

<%= render 'form' %>

<%= link_to 'Show', @trainingplan %> |
<%= link_to 'Back', trainingplans_path %>

app/views/trainingplans/new.haml
.loginColumns.animated.fadeInDown
  .row
    .col-md-6
      %h2
        .font-bold  Get your personal RACEsPACE trainingplan
        %small Bla bla bla bla blal la lwell valelb lbal.
    .col-md-6
      .ibox-content
      = simple_form_for @trainingplan do |f|
        %form#loginform.form-horizontal{role: "form"}
          .input-group{style: "margin-bottom: 25px"}
            %span.input-group-addon
            = f.input :tpracetime, :required => true, label: false, placeholder: '12000'
          .input-group{style: "margin-bottom: 25px"}
            %span.input-group-addon
            = f.input :tpunitsperweek, :required => true, label: false, placeholder: '4'
          .input-group.date
            %data_1
              %span.input-group-addon
                %i.fa.fa-calendar
                  = f.input :tpracedate
          .form-group{style: "margin-top:10px"}
            .form-actions.col-sm-12.controls
              = f.button :submit, "Makeplan"
  %hr
  .row
    .col-md-6 Copyright RACEsPACE GmbH
    .col-md-6.text.right.small © 2015-2016

  = link_to 'Back', trainingplans_path


-content_for :javascript do
  :javascript
    $(function() {
      $('#tpracedate .input-group.date')
        .datepicker({todayBtn: "linked",keyboardNavigation: false,forceParse: false,calendarWeeks: true,autoclose: true});
        });